### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by urbainvaes** [BurningEther/iron.nvim#71]
The documentation says that the plugin is free to use and extend, but I haven't found a detailed description of the rights granted to the users. For example, are users allowed to redistribute their extended version of the program? And could somebody include this program as part of a software released under a proprietary license? 

With github, you can easily choose a license from the popular options and add the corresponding file to the repository. EDIT: I see that your other repositories contain licenses, so you probably already knew about this ;)

**Comment by hkupty** [comment]
Yes, something happened when I created this one, I'm sorry. I usually take BSD or MIT licenses, so feel free to use it as you will.. I'll update this as soon as possible, adding a BSD license to it..

**Comment by hkupty** [comment]
Turns out there was a fast way for doing it. Done!

Cheers,
Henry John Kupty

**Comment by urbainvaes** [comment]
Great, thanks! :)
