### ISSUE TITLE
iron does not honor prompt color set in ipython configuration

### ISSUE THREAD

**Issue by gilgameshskytrooper** [BurningEther/iron.nvim#72]
I noticed that the IPython REPL does not honor the prompt color scheme I specified in my `ipython_config.py`

I am trying to use the red and green specified by the [Gruvbox Scheme](https://github.com/morhetz/gruvbox).

When I start `ipython` in command line, the color shows up fine.
![ipython](https://78.media.tumblr.com/d693a69b43668daeb5c812975af1b8e5/tumblr_p5k42gsWel1s5a4bko1_1280.png)

As you can see, I overrode the `Token.OutPrompt` and `Token.Prompt` colors using `highlighting_style_overrides`.

However, the same exact IPython started by iron does not reflect these overrides (despite the fact that the override values show up when I query `get_ipython().highlighting_style_overrides`

![repl](https://78.media.tumblr.com/6b97d24abfdc7f4480a03af78e163cad/tumblr_p5k42smeDv1s5a4bko1_1280.png)

I took a quick look at the source code, and I don't think you are hardcoding this anywhere.

But other than this issue, iron.nvim is the bees knees.

Thanks

**Comment by gilgameshskytrooper** [comment]
whoops. Sorry, didn't realize it was opening ptipython

**Comment by hkupty** [comment]
Don't worry, no harm done!
Glad you enjoy using iron.nvim!

Cheers,
Henry
