### ISSUE TITLE
With Clojure, can I connect to an existing REPL?

### ISSUE THREAD

**Issue by amirdlan** [BurningEther/iron.nvim#75]
I have a running Clojure REPL started somewhen. I want to connect to it and reload my vim code into it while it's running to change behavior while testing.

Hello iron.vim, am I on the right project? Thanks.

**Comment by hkupty** [comment]
Iron interacts with the current repl on a buffer basis - sending data from the code buffer to the repl buffer.
It does connect to an existing repl (with liningen) by running `lein repl :connect`.

If you are looking for nrepl commands, take a look at [acid.nvim](https://github.com/clojure-vim/acid.nvim). It was born out of the necessity to connecting to nrepl, but I didn't wan't to have that in iron, so I created a separate plugin.

Take a look at both and feel free to ping me if you still need something out of either projects.

Cheers,
Henry Kupty

**Comment by amirdlan** [comment]
ok, thanks for the clarification. I'll contact you.
