### ISSUE TITLE
tqdm incompatibility

### ISSUE THREAD

**Issue by rzpilgrim** [BurningEther/iron.nvim#76]
Using Python's tqdm package for status bars when running in IPython through :IronRepl results in a long scrolling screen rather than the expected progress bar updating behavior. The progress bar should fill without scrolling the terminal buffer.

This appears to also be an issue when using the :term command. Maybe this is a NeoVim issue?

Edit: never mind. This appears to be a result of misuse of tqdm. Sorry for posting.

**Comment by hkupty** [comment]
No problem. Feel free to post whenever in doubt.

Cheers,
Henry
