### ISSUE TITLE
let g:iron_repl_open_cmd = 'topleft vertical 80 split" error caught in async

### ISSUE THREAD

**Issue by yelled1** [BurningEther/iron.nvim#78]
Hi:

I added ```let g:iron_repl_open_cmd = 'topleft vertical 80 split'``` & used key 
    ```autocmd Filetype python nmap <localleader>\\ :call IronSend(getline('.'))<CR><ESC><C-w>jG<C-w>pj0```
and I get:

> error caught in async handler '/home/hoon/.local/share/nvim/site/plugged/iron.nvim/rplugin/python3/iron:function:IronSend [['from datetime import datetime']]'
> Traceback (most recent call last):
>   File "/home/hoon/.local/share/nvim/site/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 166, in send_to_repl
>     self.send_data(data, repl)
>   File "/home/hoon/.local/share/nvim/site/plugged/iron.nvim/rplugin/python3/iron/base.py", line 115, in send_data
>     ft = repl['ft']
> KeyError: 'ft'

but  ```autocmd Filetype python vmap <buffer> <localleader>\\ $<Plug>(iron-send-motion)```
key works fine.
Is there another command I should use?
Thank u much,

Hoon,

**Comment by yelled1** [comment]
Thank u - that split timing issue w
ould not have crossed my mind ;)

**Comment by hkupty** [comment]
You might as well try something like this:
`nmap <localleader>\\ :call IronSend(getline('.'), &ft) \| IronFocus<CR>`

It will automatically focus on the repl buffer.
